### ISSUE TITLE
Integrate antigrief module

### ISSUE THREAD

**Issue by Brickcaster** [factoriommo/factoriommoscenarios#21]
I think the rest of the fMMO community would benefit from using my antigrief module.  This module is designed to be entirely standalone and requires nothing more than an include and the (already present) Event module.

Line 36 won't interfere with anything, but I tie permissions into RPG levels and higher level players get a warning before a ban.  You could change the condition.

The file is here: https://github.com/Brickcaster/factoriorpg/blob/oarc-scenario/utils/antigrief.lua

**Comment by IBlackI** [comment]
It would be nice to integrate this into the modular_admin gui aswell, possibly adding a button to teleport / spectate the player causing the alert.

**Comment by Brickcaster** [comment]
The alert() function creates an in game alert that can be clicked to teleport the camera to the relevant player.  That's already part of the module.

**Comment by IBlackI** [comment]
Added
