### ISSUE TITLE
top_gui design idea: promote() and demote() methods

### ISSUE THREAD

**Issue by Brickcaster** [factoriommo/factoriommoscenarios#22]
Instead of using a top_gui method to create elements, add a promote() and demote() method which deepcopies gui elements and then recreates the entire gui from the read data.  This design style would be more modular and would not require other modules to use it's specific methods when adding to the gui. 
 The method for deep copy is a Factorio utility script so it should be easy to utilize.

Additionally, you could add a "insert_at_index" method for modules which are aware of your top_gui script so they can take the most recently added item (The one at the end of the list) and move it to the specified index.

**Comment by IBlackI** [comment]
I do not directly see an advantage to this solution over the already established code. Wouldn't the code using those methods need to be aware of that module? If the code needs to be aware of an module already I don't think it really matters which one. 

Top_gui is however implemented to be able to use mod_gui so if another module uses that it shouldn't result in a conflict. Top_gui will however not be able to determine their order ofcourse.

**Comment by Brickcaster** [comment]
An example would be the Player List module I use. Rather than redesigning Player List to utilize the top_gui creation method, I could register an event on_player_created (after the player list event) to do top_gui.promote("player_list_button") to move it up one step.

Likewise, if anything were to add buttons later in the game, like say a rockets launched gui that only appears after rockets have been launched, then an event listener could be added for that as well such that it can be moved to the desired position.

This makes it easier to add additional modules and keep them up to date as the management becomes something external to the module and not an internal part that must be modified when updating.

**Comment by IBlackI** [comment]
An problem I forsee is that top_gui would have to remove and recreate the gui element to fit in its own flow. If an module is hardcoded to game.player.gui.top.button.caption = "changed" it would cause errors in that module because the gui element is no longer valid. 

A way around this would be ofcourse to change the visible property of the element but I do not know how top_gui could listen to that guielement and update if it gets changed.

**Comment by Brickcaster** [comment]
That is already a problem with top_gui.  Moving gui elements (via destruction and re-creation) breaks any references to elements and changing the method that elements are re-arranged does not change that.

Any references that work via name would be unchanged.

Gui-related modules should be working within the mod_gui flow anyhow and top_gui should be no exception.

**Comment by IBlackI** [comment]
The modules that use top_gui have adapted to calling the top_gui methods for changing the element/re-adding it. Even if you were to use a demote and promote method wouldn't you also have to change the calls altering the elements?

**Comment by IBlackI** [comment]
Closed due to not seeing the need for this feature.
