### ISSUE TITLE
[New command] Clear all ghosts

### ISSUE THREAD

**Issue by psihius** [factoriommo/factoriommoscenarios#29]
We got a griefer today that spammed the whole map with blueprints, and I couldn't google the command on how to clear those (Mylon helped by giving me a command to run).

So I propose we add it as command (same as we had biter corpse clearing command)

```/c for k,v in pairs(game.surfaces[1].find_entities_filtered{name="entity-ghost"}) do v.destroy() end```

**Comment by IBlackI** [comment]
There is no place to add this in the current toolstack. This would be possible to add to the 0.15 branch but I don't think that is being used anymore.

**Comment by Brickcaster** [comment]
We don't need a button for every possible scenario.  This might only ever get clicked 1-3 times a year.
