### ISSUE TITLE
GUI suggestion: Add close buttons to information screen

### ISSUE THREAD

**Issue by Brickcaster** [factoriommo/factoriommoscenarios#31]
Having an X to click on at the top right would be more intuitive than clicking the red "Close information screen" at the top.  It's common for players to ask how to close it when they join.

**Comment by IBlackI** [comment]
The current GUI design does not have space for that button, do you have any recommendation on where to put it?

**Comment by Brickcaster** [comment]
![image](https://user-images.githubusercontent.com/13324089/37038005-9bec26f2-2121-11e8-8ffb-a7426e66202d.png)

The gui probably doesn't have space for the x to be on the same line as the frame caption.  My RPG module has the same problem.  If there's no where to add an X then oh well.  We can still add a button on the left.

Additionally, if you set player.opened to the gui element, the player can remove it by pressing "e" or "esc", improving usability further.

**Comment by IBlackI** [comment]
Thank you for the player.opened tip, I will look into it.

I could theoretically place the X there as a label instead of a button which will still make it clickable just not as obvious.

**Comment by IBlackI** [comment]
Forgot that the header of a frame is an actual built in caption and not a label element. Will have to reconsider approach.

**Comment by psihius** [comment]
Implemented
