### ISSUE TITLE
Information pane: Remove 'unselected' state

### ISSUE THREAD

**Issue by Brickcaster** [factoriommo/factoriommoscenarios#32]
Seems silly that there is a blank state for this widget.  If someone clicks the same category twice, just leave it on that category instead of reverting to the "no information selected" pane.

**Comment by IBlackI** [comment]
Unselected state is required due to modular nature. What would happen if there were no submodules?

Option to disable being able to unselect an category might be considered tho.

**Comment by IBlackI** [comment]
Change global.modular_information.button_must_be_selected to true to force a submodule to be active at all times.

This setting makes it so you can't change the current button to "none"
